language: scala
dist: trusty
scala:
   - 2.12.3
   - 2.11.11

jdk:
  - oraclejdk8

matrix:
  include:
  - jdk: openjdk7
    scala: 2.11.11

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

